spring:
   jpa:
      show-sql: "true"
      properties:
         hibernate:
            dialect: "org.hibernate.dialect.Oracle12cDialect"
   datasource:
      driver-class-name: "oracle.jdbc.driver.OracleDriver"
      url: "jdbc:oracle:thin:@localhost:1521:xe"
      username: "vvs"
      password: "vvs"
      testWhileIdle: "true"
      validationQuery: "SELECT 1 from dual"
